# fly.toml app configuration file generated for fly-frp-red-sun-4121 on 2024-10-30T19:36:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-frp-red-sun-4121'
primary_region = 'hkg'
kill_signal = 'SIGTERM'
kill_timeout = '2m0s'

[build]

[http_service]
  internal_port = 80
  force_https = true

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 80

  [[services.ports]]
    port = 80

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 443

  [[services.ports]]
    port = 443

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 2222

  [[services.ports]]
    port = 2222

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 8080

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 8022

  [[services.ports]]
    port = 8022

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 7000

  [[services.ports]]
    port = 7000

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'udp'
  internal_port = 7000

  [[services.ports]]
    port = 7000

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'udp'
  internal_port = 7001

  [[services.ports]]
    port = 7001

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 25565

  [[services.ports]]
    port = 25565

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'udp'
  internal_port = 19132

  [[services.ports]]
    port = 19132

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
